### PR TITLE
Timer skips seconds

### LINKED ISSUE #90: Timer skips seconds
**Describe the bug**
The timer skips seconds from time to time <sup>(pun intended)</sup>. For example, it may go from 53 to 51 without seeing 52.

**To Reproduce**
1. Set timer to 1 minute
2. Watch it count down and observe it skipping numbers

**Expected behavior**
It shouldn't skip numbers.

**Desktop (please complete the following information):**
 - OS version: macOS 10.15.5
 - Version: 1.5.4

### PR DESCRIPTION
**Pull request by karbassi**
Fixes #90

### CODE REVIEW

**Comment by karbassi** [comment]
Can someone test this other than me? @robinstewart @luckman212

**Comment by karbassi** [comment]
Will merge this week if no one has objections.

**Comment by luckman212** [comment]
Sorry for the delay, I am cloning and compiling this branch now to test 👍  
thanks @karbassi

**Comment by luckman212** [comment]
LGTM @karbassi — no more skipped seconds! 🎉 
Timer_b

**Comment by robinstewart** [comment]
I don't understand why this code change would fix anything. If anything, increasing the tolerance will make the bug behavior more likely to appear. Similarly, _decreasing_ the tolerance won't fix the bug because it's just a hint to the system of what timer variance is ok with your app.

The only approach I can think of to truly fix this is to detect where the seconds boundary is when the timer starts, then start the repeating timer at a time that's not too close to the seconds boundary.

Also, to truly test this you need to view the countdown showing milliseconds (either on the watch face or in debug print statements). Then you can see if your fix consistently avoids the seconds boundary.

Sorry I haven't had the time to work on this myself.

**Comment by luckman212** [comment]
@robinstewart After thinking about it, I agree with what you said. It doesn't really make sense to have the countdown tick display calculated from the system clock since there will inevitably be some small drift and jumps/skips if the timer is started close to a second boundary.

I just resubmitted a PR - https://github.com/michaelvillar/timer-app/pull/93 that works for me. Please test if you can.

**Pull request closed without merging**
