### PR TITLE
Use a fixed-width font for less jank

### LINKED ISSUE #85: Use a fixed-width font and leading zeros for less jank
Hi

**Is your feature request related to a problem? Please describe.**
I notice little movements of the timer's contents—aka "jank"—out of the corner of my eye which is distracting

**Describe the solution you'd like**
* Use a fixed width font, please, so that, e.g., `51"` → `50"` doesn't move around
* Use leading zeroes, please, so that, e.g., `10"` → `9"` doesn't move around (it would be `10"` → `09"`)

**Describe alternatives you've considered**
Hiding the Timer window, but when screen sharing that would make it hard for all participants to be aware of our current interval

Cheers!

### PR DESCRIPTION
**Pull request by karbassi**
- Change to monospacedDigitSystemFont
- Remove old version checks
- Update build target to 10.11, as set by the project

Fixes #85

### CODE REVIEW

**Comment by robinstewart** [comment]
Can you post a few screenshots?

**Comment by karbassi** [comment]
See if you can spot which one is the before and which is after.

before after

<sub><sub>right one is after</sub></sub>

**Comment by karbassi** [comment]
@robinstewart @michaelvillar Shall I merge?

**Comment by robinstewart** [comment]
Does this also affect the red time text? If so can you post what it looks like unpaused or at zero remaining seconds?

**Comment by nvenegas** [comment]
@karbassi thanks for doing this!

@robinstewart it doesn't affect the red text (9:19am is the current release, 9:24 is a build from this branch)

current-release monospace

**Pull request merged**
