### PR TITLE
"C" key to "clear" timer

### PR DESCRIPTION
**Pull request by robinstewart**
I have muscle memory from using the built-in calculator app that the <kbd>C</kbd> key clears out any numbers. Synonym of <kbd>Escape</kbd>.

### CODE REVIEW

**Comment by karbassi** [comment]
@robinstewart any other apps use <kbd>c</kbd> to clear?

**Comment by robinstewart** [comment]
@karbassi I don't know. I've only used it in Calculator.

**Comment by karbassi** [comment]
@robinstewart I think for the sake of keeping the app simple and not adding multiple keys for each action, we should keep it to just <kbd>esc</kbd>

**Comment by robinstewart** [comment]
Totally agree with importance of keeping the app simple to use. Can we achieve that by leaving this synonym undocumented? Just an invisible shortcut for people like me who use the calculator a lot and reflexively hit "c" for "clear".

Not a big deal either way, this has just come in handy during my testing.

**Comment by dwainm** [comment]
Escape works for clear.

**Comment by karbassi** [comment]
Closing for now to keep things simple.

**Pull request closed without merging**
