### PR TITLE
Add badge

### LINKED ISSUE #17: Update mac osx doc icon with actual time
It would be awesome if the app also updated the dock icon with actual time left so I wouldn't have to click the icon to know how much time has passed.

### PR DESCRIPTION
**Pull request by DummybugStudios**
Adds the time remaining to the tile badge in the dock so users can quickly tell the time they have left.
Get the context menu by right clicking the window and choose "show in dock"
Closes #17

### CODE REVIEW

**Comment by michaelvillar** [comment]
Could you share a screenshot of what it looks like?

**Comment by DummybugStudios** [comment]
screen shot 2018-06-07 at 09 11 20
Here's the screenshot! :)
The badge disappears when the timer turns off.
You can also choose which timer shows in the dock :)

**Comment by michaelvillar** [comment]
Thanks 🎊

**Comment by akarki15** [comment]
I am a little late, but thanks for doing this @DummybugStudios!

**Pull request merged**
